[package]
name = "lemurs"
version = "0.1.0"
edition = "2021"
rust-version = "1.58"
description = "Linux eBPF Monitoring using Rust"
homepage = "https://github.com/syscll/lemurs"
repository = "https://github.com/syscll/lemurs"
license = "GPL-3.0"
keywords = ["linux", "ebpf", "monitoring", "metrics"]
readme = "README.md"

[dependencies]
nix = "0.23"
clap = { version = "3.0", default-features = false, features = ["cargo", "std"] }
anyhow = "1.0"
