[package]
name = "lemurs"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"
description = "Linux eBPF Monitoring daemon"
homepage = "https://github.com/loshz/lemurs"
repository = "https://github.com/loshz/lemurs"
license = "GPL-3.0"
keywords = ["linux", "ebpf", "monitoring", "metrics"]
readme = "README.md"

[dependencies]
libbpf-rs = "0.16"
nix = "0.23"
clap = { version = "3.0", default-features = false, features = ["cargo", "std"] }
anyhow = "1.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
metrics_server = "0.1"
