[package]
name = "lemurs"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"
description = "Linux eBPF Monitoring daemon"
homepage = "https://github.com/loshz/lemurs"
repository = "https://github.com/loshz/lemurs"
license = "GPL-3.0"
keywords = ["linux", "ebpf", "monitoring", "metrics", "prometheus"]
readme = "README.md"

[dependencies]
libbpf-rs = "0.16"
libc = "0.2"
nix = "0.23"
clap = { version = "3.1", default-features = false, features = ["std", "derive"] }
anyhow = "1.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
metrics_server = "0.5"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "signal", "time"] }
log = "0.4"
simplelog = "0.11"
prometheus-client = "0.15"

[build-dependencies]
libbpf-cargo = "0.10"
