name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_VERSION: 1.61
  LIBBPF_VERSION: 0.8.0

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}

      # Install clang and required tooling.
      - run: sudo apt update -y && sudo apt install -y clang-10 libelf-dev

      # Install libbpf.
      - run: |
          sudo mkdir -p /usr/include/bpf/
          curl -sSL "https://github.com/libbpf/libbpf/archive/refs/tags/v${{ env.LIBBPF_VERSION }}.tar.gz" -o /tmp/libbpf.tar.gz
          sudo tar -xvf /tmp/libbpf.tar.gz --strip-components=2 -C /usr/include/bpf "libbpf-${{ env.LIBBPF_VERSION }}/src/bpf_helper_defs.h" "libbpf-${{ env.LIBBPF_VERSION }}/src/bpf_helpers.h"

      # Generate BTF headers.
      - run: make btf
      
      # Install Rust tools.
      - run: |
          rustup component add rustfmt clippy
          cargo install --locked cargo-deny

      # Run security audit checks.
      - run: cargo deny check

      # Lint code and run tests.
      - run: |
          cargo fmt -- --check
          cargo clippy --tests -- --no-deps -D warnings
      - run: cargo test --no-fail-fast
